[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python railway_start.py"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Resource optimization
[env]
NUM_WORKERS = "1"
WEB_CONCURRENCY = "1"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"

[phases.setup]
nixPackages = [] # Remove postgresql 